### ISSUE TITLE
Parcours répertoire

### ISSUE THREAD

**Issue by maitrepylos** [nml18/esa_php#2]
Salut,

Ton exo, tu l'as fais toi même où tu t'es aidé d'un tuto.
Juste pour savoir si tu as compris tout ce que tu as fais, notamment les includes ?

**Comment by nml18** [comment]
Bonjour,

Je me suis documenté au niveau des importations de fichiers pour mieux organiser mon travail (pour l'exo damier également).
Je me suis permis de le faire, car c'est quelque chose qu'on vient de voir avec André en PAPR.
Je suis conscient du fait qu'on n'ait pas vu cela encore au cours (je peux réorganiser mon code si cela pose problème).

Concernant la partie algorithmique, je me suis renseigné sur chacune des fonctions et leur fonctionnement via https://www.php.net/docs.php.
Notamment sur le fait que le pointeur qui est défini à l'aide du **opendir()** s'incrémente à chaque appel de la fonction **readdir()** (ce que j'ignorais au départ).

Je suis également intéressé par votre retour sur le travail du damier (si cela est toujours possible) :smile:

**Comment by maitrepylos** [comment]
OK, alors si tu veux prendre de l'avance.
Je te conseilles de chercher require et require_once, qui sont des méthodes plus adaptés et que je préconise en place et lieu de include.
Une fois ce concept maitrisé , recherche les concepts de PSR en PHP et notament la gestion des namespaces (qu'on ne devrais pas voir cette année). Si j'ai le temps je checke le damier.

**Comment by nml18** [comment]
Merci pour le retour.
Je vais faire des recherches sur ces sujets et adapter mon code pour les prochains exercices.
